### ISSUE TITLE
feature: show Standard as default number or add option to chose 

### ISSUE THREAD

**Issue by lebed2045** [k06a/GasTray#2]
The problem
<img width="198" alt="Screen Shot 2021-01-04 at 10 54 50 AM" src="https://user-images.githubusercontent.com/1270800/103518582-d7a5e800-4e95-11eb-9220-c5332932d28e.png">
when the widget shows 10 gWei - it gives user a false impression of a cheap gas, "standard" would be more relevant to chose to reality (which is x25 of that right now!).

Some traders might be more interested to see "Fast", so to chose tx speed it might be even more useful.

**Comment by k06a** [comment]
Fixed! https://github.com/k06a/GasTray/releases/tag/0.0.4
